remote_theme: "mmistakes/minimal-mistakes@4.17.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
#  - jekyll-algolia
minimal_mistakes_skin: "dark" # "default" # "air", "aqua", "contrast",
title: "The"
subtitle: "No"
breadcrumbs: true
search: true
#search_provider: algolia
twitter:
  username: "test"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
